### ISSUE TITLE
Change name repo

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-web#1]
Please don't use repo with version behind the name change name from pijar-cooking-web-v3 to pijar-cooking-web in setting.

**Comment by isnancahyadi** [comment]
I have fixed it. Thank You.
![Screenshot (145)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/1142d4d7-d854-48b2-a8db-7033fba45315)

**Comment by kubil-ismail** [comment]
Done
<img width="1680" alt="Screenshot 2023-08-10 at 00 14 08" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/dba952bc-5642-44c4-86be-40fc95e726ee">
