### ISSUE TITLE
Fix search logic

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-web#2]
![Screenshot (98)](https://github.com/isnancahyadi/pijar-cooking-web-v3/assets/49361887/9f4e6672-1b05-4b56-82a3-859b165e77c2)

Fix search logic in backend using ilike for ignore font capitalization, example search Siomay and siomay is different result.

**Comment by isnancahyadi** [comment]
I have fixed it. Thank you.
![Screenshot (147)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/5564c06d-ee03-4f38-a8c0-b38047ae55c9)
![Screenshot (148)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/17fb855d-ee06-4665-9289-c5da24d5b738)

**Comment by kubil-ismail** [comment]
solved
<img width="1680" alt="Screenshot 2023-08-10 at 00 23 23" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/fb405691-5fc6-4261-a86b-779b1e417e5c">

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 00 23 37" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/6276bc2f-1de8-4fd9-89f3-621b0ff8536c">
