### ISSUE TITLE
Error on click learn more

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-web#3]
in home section New Recipe, click learn more button, redirected to https://pijar-cooking-web-v3.vercel.app/detail/siomay-bandung?18, i got error data not found and check your network info got this. Please fix okay
![Screenshot (101)](https://github.com/isnancahyadi/pijar-cooking-web-v3/assets/49361887/93afd45b-90d0-4ce2-a99d-7bc69827cd1b)

**Comment by isnancahyadi** [comment]
I have fixed it. Thank you.
![Screenshot (149)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/52dc50ff-5ab5-4d00-9272-47910513a86b)

**Comment by kubil-ismail** [comment]
Done
<img width="1680" alt="Screenshot 2023-08-10 at 00 26 53" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/ec4fa0c8-54e3-4a5b-850c-abffe0eb9b62">
