### ISSUE TITLE
Error after register

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-web#4]
Please fix your login system, if u just need login with username delete label username or email in login area. I try login with my email and always get wrong, after check my network i realize you only send username not email. Thanks

**Comment by isnancahyadi** [comment]
I'm sorry. I have checked again using the existing link, there are no errors in the login system using email. Maybe it's because the email or password you've input is wrong, so that throwing account not found. That's my bad to throw that response, I'll fix it. Thank you.

**Comment by isnancahyadi** [comment]
I have fixed it. If you still find that error, please make new issue. Thank you.
![Screenshot (146)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/1285c2e9-d9e2-4d2c-97ce-06d4f748cfa2)

**Comment by kubil-ismail** [comment]
Done. register and login successfully
<img width="1680" alt="Screenshot 2023-08-10 at 00 20 33" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/46a4a3d6-f8c0-4749-b4e1-a838f3f89306">

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 00 20 55" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/7282f32a-44d9-43ce-9701-41ebeec59d16">
