### ISSUE TITLE
Got error in add recipe

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/pijar-cooking-web#5]
![Screenshot (102)](https://github.com/isnancahyadi/pijar-cooking-web-v3/assets/49361887/ec25bff1-3078-449f-b1df-1725b2094ae0)
Please check in add recipe i got error, make loading in button submit and info user if bad happen in uploading for user experience.

**Comment by isnancahyadi** [comment]
I have fixed this error. Thank you.
![Screenshot (150)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/ddb5f6b9-ea82-4957-ad48-958a2dc71337)

**Comment by kubil-ismail** [comment]
error message showing , button loading is showing while process submit, But add recipe still failed
<img width="1680" alt="Screenshot 2023-08-10 at 00 31 14" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/7fe81e9f-c389-46db-a455-659909f4d243">

**Comment by isnancahyadi** [comment]
I have fixed it. There is bug in server.
![Screenshot (153)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/8aa3f55c-d560-47a5-a062-31b88410f2a5)

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 10 30 07" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/6099269d-d2e1-46a1-8cac-1fbe88678b66">

title: Tahu bulat
ingredients: tahu,micin
image: (binary)
video: https://www.youtube.com/watch?v=ZYJ3PHMzeHg&t=1s
direction: tahu,minyak,bulat
category: 2
description: Tahu bulat adalah sebuah jajanan kaki lima berupa olahan kacang kedelai yang dibuat menjadi sebuah tahu berbentuk bulat dengan isi kopong. Biasanya, tahu bulat dijual di sebuah mobil bak terbuka dan kebanyakan dihargai Rp 500 an dan disajikan hangat.

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 10 30 07" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/6099269d-d2e1-46a1-8cac-1fbe88678b66">

title: Tahu bulat
ingredients: tahu,micin
image: (binary)
video: https://www.youtube.com/watch?v=ZYJ3PHMzeHg&t=1s
direction: tahu,minyak,bulat
category: 2
description: Tahu bulat adalah sebuah jajanan kaki lima berupa olahan kacang kedelai yang dibuat menjadi sebuah tahu berbentuk bulat dengan isi kopong. Biasanya, tahu bulat dijual di sebuah mobil bak terbuka dan kebanyakan dihargai Rp 500 an dan disajikan hangat.

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 10 30 07" src="https://github.com/isnancahyadi/pijar-cooking-web/assets/49361887/6099269d-d2e1-46a1-8cac-1fbe88678b66">

title: Tahu bulat
ingredients: tahu,micin
image: (binary)
video: https://www.youtube.com/watch?v=ZYJ3PHMzeHg&t=1s
direction: tahu,minyak,bulat
category: 2
description: Tahu bulat adalah sebuah jajanan kaki lima berupa olahan kacang kedelai yang dibuat menjadi sebuah tahu berbentuk bulat dengan isi kopong. Biasanya, tahu bulat dijual di sebuah mobil bak terbuka dan kebanyakan dihargai Rp 500 an dan disajikan hangat.

**Comment by isnancahyadi** [comment]
Fixed. Thank You.
![Screenshot (155)](https://github.com/isnancahyadi/pijar-cooking-web/assets/97781402/9fb1d017-ffc3-4823-a861-0ad015912d26)
